name: Client CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
      if: ${{ startsWith(github.event.head_commit.message, 'client:') }}
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: notryuk
          password: dckr_pat_KI3LKpEemqoZxUxu2RJoZbFxUuk
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.client
          push: true
          tags: notryuk/mascot-client:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
        - name: Pull image from docker hub
          run: docker pull neam6009/propertywala_frontend:latest
        - name: Delete old container
          run: docker rm -f propertyWala-frontend-container
        - name: Run Docker Container
          run: docker run -d -p 5173:80 --name propertyWala-frontend-container neam6009/propertywala_frontend
