name: Server CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master


jobs:
  build:
    if: ${{ startsWith(github.event.head_commit.message, 'server:') }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: notryuk
          password: dckr_pat_KI3LKpEemqoZxUxu2RJoZbFxUuk
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.server
          push: true
          tags: notryuk/mascot-server:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from DockerHub
        run: sudo docker pull notryuk/mascot-server:latest

      - name: Delete old Container
        run: sudo docker rm -f mascot-server-container || true
      
      - name: Re-run the Docker Container
        run: sudo docker run -d -p 6969:6969 --name mascot-server-container notryuk/mascot-server:latest
